language: node_js

node_js:
  - "6"
  - "7"
  - "8"

install:
  - npm install

script: npm test

before_deploy: npm run pack
deploy: 
  provider: releases
  api_key:
    secure: "YhXqIUeKIBCbZynC2xx92qw2W/T2H/bx3U5O4rbWeO1ZZaHNd7RkLqjzC7/seiqqqVK4gqKxVAB1gFOaaqL7HDIC9M68ol/0f3PbrKLqg+FvHFOW6eqTJNlWAG37Xr2+Sy1Dcul4e8G/lE4wzwA6JrCkj87lZ1oymkSWdztWneLP6kQMnaFszcm5nUvKH75fRycg+bmc6Hhwqm6wLKQmkN2zGtjbo9z7FEeQCZAqReYT4nx3znjakD+Z7t4RzCo9wCcZdTYmrgWKabNk6qPsHIvW4zEwQe4u2A3S/zd0rMz4R6OCPQECVqVre/a8K+UYLmR1+56hWhpLjya4qEtjn1beMyyI/WmlGCogZupUrHNr1MD8F+zPhmQsUsg9NY9TTR5sI5vMQMD6yYW1QHSr/127xnDWAcMdsupDFya8o/vNsheFW1gqfm37HC9BpR4d0cIYXgdaFGLsN4GT6Nj/vzzCaSVhRjioutMfjggaje4mWr3K75o9bDuc7AgZQxfcfqRHXEaMZf7vLdLvkSCh+1lWokNYPRGj4R47FHg1tKF1jTeJoi7V/J4//bXgoF2zU0GN7g6L69BsJf6HtaOtDjNs2tdhP6x7aNeuFNV9tEcuzwjE4TJZm2vov9Yf32STg//a/ZyUS98Hoj8JF4PEeUzmS94MF1jW6UVofSsBi1A="
  file_glob: true
  file: "packed/*"
  skip_cleanup: true
  on: 
    tags: true