language: node_js

node_js:
  - "6"
  - "7"
  - "8"

install:
  - npm install

script: npm test

before_deploy: npm run pack
deploy: 
  provider: releases
  api_key:
    secure: "IeZjxbgEvlt4eoyOwEd+AZoppjCMcf+739RdmNAH2psenTJM9pCeWmg6VqlBBBOD6LAxtuczOLdLwS8YhvF+n+k/rGBFoKJ5Wvv+6VYZOurMx/yHgRpEmwa0GwDxw48d6uqM7QQT7rpYSpeOuna7nkXYWVzdn+2ADMz3JTCugybzHZrxwLh5DVmFlVHgGXaImdJRwSjbsVpokvW8krVKuU2ksuaK1ASALQoXHXEOHCrjWeOnBG7DQ0egn0i2TdEHN807tzEubhwtVvGF11laW6hBAEhVyZqZZhYz5XbeUxiq+2nzkIg5Fs6sZehkbJKq8GDj53q3CRTONVdNsz6sjtfdBjd2IoSnXGLuy0NUDbRV0XElwMaxDqp1FRrx8iyr72QbzJjnHD1li+B5jpDp39ivmPOC/cE3HkaJZ1M94ltv0DNr84d+8tHN3mMrA33wlJhaiVZIx6GW+6hr/jDICesQHsRwKk7WtPW6jflE008ifXS9qK9XZwkR06IasUsoOha6DgRH+r8ENTRUqJp7WTJLaEegNUD7YLCBLzTOLhcQUbte+WaBSYG5XK2GGki0W6a5VCZM+AyuuoNrz5xlQaN6JiU1yEmDKQFZDL9tDNGlK/wzQwvN1Ci+BLfHaTho2D2h4V3XjdQKLsqXQl0ee1HkuZuLAHnqp/PFrvafpdI="
  file_glob: true
  file: "packed/*"
  skip_cleanup: true
  on: 
    tags: true