language: node_js

node_js:
  - "6"
  - "7"
  - "8"

install:
  - npm install

script: npm test

before_deploy: npm run pack
deploy: 
  provider: releases
  api_key:
    secure: "o7priNsLI/kzraVx9QSRNrXoMRzb/Ehm4Uw+p1viyK5uPOwUICM0wz7xBNou6qa8kOjrCYVIQ7QPki1duTqqGgBizT4PhNP7J8fgWvo2JMEkWaHmZyIhdNmnrigze2IqKh7Mi47A9NV8LvfiJE5GvzdYqKP53ZZkGSSqiV0k7ZPZ1xlTaFNoEPTKaj5b/H+diZs9Ycg41POrU9jxSyHzg8Y8O6nLqTrm+NntEjbYL72SzR4uigUrz2kQ8AeGoc5x/E7r0t1Kls/ttCwkv7qf/m5c53GV0twBNngFFKDTEX1d2PH23d0DfdOlIhaCOK/U+aVVwz7PuNLtOuZrUCsLv6Dw8m0MfV3TdtD+HUOL2/Tgo97f44t65PY2+bcBjwvV1BJawm1j1e2NNVYFmO5y8lkUIPzP2cCp1k17PXiXxoRaQp/aDaJyP7TrfCBImJw9m9gVn6Kes5GlTqlxvBMs2CxwQ8X5Iclz9ldkNIO0H6Pa4UwmYacoGH1nWhrsY7S0JfTQ3Uob3YhvMgkN5ZT6dhPIM+yx54qSneA2KKl+sDz6PgBrwI9TyF6/eaLf+QkgnO4PxCOuPp1QnrTOjIzES0PRSa1z76zlz++u3pdBiOB8fn8bSwoHZDi3Y1/qQsq034+bysdWDt2CbSLMHbuSSyIFXQpUQsXUkRFFOsXcKUE="
  file_glob: true
  file: "packed/*"
  skip_cleanup: true
  on: 
    tags: true